# Use a Node base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY client/package*.json ./
RUN npm install

# Copy the rest of the frontend code
COPY client/ ./

# Expose React dev server port
EXPOSE 3000

# Start React app (dev mode)
CMD ["npm", "start"]
